### ISSUE TITLE
Map Yabeda units to DataDog units

### ISSUE THREAD

**Issue by palkan** [yabeda-rb/yabeda-datadog#15]
I'm using `yabeda-datadog` along with `yabeda-sidekiq`.

The data displayed in DataDog doesn't contain units for histograms:

<img width="992" alt="image" src="https://user-images.githubusercontent.com/1516722/51492250-30e6e080-1d7f-11e9-9f92-0989c5518c1d.png">

I guess, that's because `yabeda-sidekiq` uses plural form (`:seconds`) and we have `"second"` in the list of available units (https://github.com/yabeda-rb/yabeda-datadog/blob/master/lib/yabeda/datadog/units.rb) (btw, shouldn't we take care of symbols vs. strings too?).

We need a way to map yabeda units to DD units.

Also, counters have fractional values (not sure, what the unit should be for them to be displayed correctly):

<img width="558" alt="image" src="https://user-images.githubusercontent.com/1516722/51492387-9fc43980-1d7f-11e9-8aa4-02732f7dfa26.png">

**Comment by palkan** [comment]
Upgraded to the latest version, and still see the same fractional values.

Could this be because of Datadog didn't update the units for these metrics? Should I recreate them or what/

**Comment by shvetsovdm** [comment]
PR #16 does not address the fractional values issues. I will try to solve this issue separately.

**Comment by palkan** [comment]
> I will try to solve this issue separately.

Sound good) Let me know when I should I try it again)

**Comment by shvetsovdm** [comment]
@palkan can you try this:

1. clone your "jobs counter" panel (if you still have [this](https://user-images.githubusercontent.com/1516722/51492387-9fc43980-1d7f-11e9-8aa4-02732f7dfa26.png) panel with `jobs_enqueued_total`, `jobs_failed_total`, `jobs_waiting_count ` metrics) 
1. remove only `jobs_waiting_count ` metric from cloned panel
1. check if it solves the "fractional" issue

I think the "fractional" problem appears when _count_ and _gauge_ metrics combined in one panel.

**Comment by palkan** [comment]
<img width="701" alt="image" src="https://user-images.githubusercontent.com/1516722/53653686-e11af500-3c19-11e9-84f9-c1f972474552.png">

@shvetsovdm didn't help(

**Comment by shvetsovdm** [comment]
ok, I will study the issue further. Thx for the config.

**Comment by shvetsovdm** [comment]
@palkan please try in _metrics summary_ page change your "fraction" metrics from _count_ type to _rate_ type with interval 10. This solves the issue in Datadog app for me.

If this is a cure for the issue then I will implement a fix.

**Comment by palkan** [comment]
Thanks! That helped)

What about gauge metrics?

**Comment by shvetsovdm** [comment]
> Thanks! That helped)

Nice! 🎉 

> What about gauge metrics?

I will investigate it further

**Comment by shvetsovdm** [comment]
>  What about gauge metrics?

Gauge metrics should just work. If you remove it from your graph as I recommended earlier, get it back.

It turns out that _count_ metrics in Datadog, in reality, is _rate_ metrics over flush interval, 10 seconds by default.

yabeda-datadog sends metrics as _rate_ type and after the gem registration methods are called this metrics metadata updated and their type becomes counters. Counters have no flush interval and Datadog graphing show it as raw values which is divided by the flush interval which is 10. That why we have decimal values.

Hope it makes sense.

By the way, be aware next time you restart/run an application with yabeda-datadog the metrics will be updated from _rate_ to _count_ again and the fractional problem will come back. I am working on a fix for this.

**Comment by shvetsovdm** [comment]
Since this issue is related to Datadog/yabeda units, I close it in favor of https://github.com/yabeda-rb/yabeda-datadog/issues/17
